MB-61889: Address corner case with ivf_nprobe_pct
+ With certain cluster counts within centroid indexes, a very
  low value for ivf_nprobe_pct can cause nprobe to be rounded
  down to 0, which would result in this error ..
```
Error in virtual void faiss::IndexIVF::search(
faiss::idx_t, const float*, faiss::idx_t, float*,
faiss::idx_t*, const faiss::SearchParameters*) const at
/home/couchbase/.../faiss/faiss/IndexIVF.cpp:310:
Error: 'nprobe > 0' failed
```
+ In this event, we should be rounding up nprobe to 1 instead.